import { StorefrontLayout } from "@/components/StorefrontLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function AccountAuth() {
  const [, setLocation] = useLocation(); const [mode, setMode] = useState<"login" | "register">("login"); const [recoveryOpen, setRecoveryOpen] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [password, setPassword] = useState(""); const utils = trpc.useUtils();
  const login = trpc.auth.passwordLogin.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); setLocation("/profile"); }, onError: error => toast.error(error.message) });
  const register = trpc.auth.register.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); setLocation("/profile"); }, onError: error => toast.error(error.message) });
  const recovery = trpc.auth.passwordResetRequest.useMutation({ onSuccess: () => { setRecoveryOpen(false); toast.success("If an eligible account exists, restaurant staff will follow up."); }, onError: () => toast.success("If an eligible account exists, restaurant staff will follow up.") });
  const submit = () => { if (mode === "register") register.mutate({ name, email, phone, password }); else login.mutate({ email, password, role: "customer" }); };
  const pending = login.isPending || register.isPending;
  return <StorefrontLayout><main className="container py-16"><section className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm"><p className="eyebrow">Customer account</p><h1 className="mt-2 font-serif text-4xl font-semibold">{mode === "login" ? "Welcome back" : "Create your account"}</h1><p className="mt-3 text-sm text-[#74695b]">Securely save addresses, checkout, and view your orders.</p><div className="mt-6 flex rounded-xl bg-[#fbf8f2] p-1 text-sm"><button type="button" onClick={() => { setMode("login"); setRecoveryOpen(false); }} className={`flex-1 rounded-lg py-2 ${mode === "login" ? "bg-white font-bold shadow-sm" : "text-[#74695b]"}`}>Sign in</button><button type="button" onClick={() => { setMode("register"); setRecoveryOpen(false); }} className={`flex-1 rounded-lg py-2 ${mode === "register" ? "bg-white font-bold shadow-sm" : "text-[#74695b]"}`}>Register</button></div><div className="mt-6 space-y-3">{mode === "register" && <><Input value={name} onChange={event => setName(event.target.value)} placeholder="Full name" /><Input value={phone} onChange={event => setPhone(event.target.value)} placeholder="Phone number" /></>}<Input value={email} onChange={event => setEmail(event.target.value)} type="email" placeholder="Email address" /><Input value={password} onChange={event => setPassword(event.target.value)} type="password" placeholder="Password (12+ characters)" /><Button onClick={submit} disabled={pending} className="w-full bg-[#ae3f25]">{pending ? "Please wait…" : mode === "login" ? "Sign in" : "Create secure account"}</Button>{mode === "login" && <button type="button" className="w-full text-sm font-semibold text-[#ae3f25]" onClick={() => setRecoveryOpen(current => !current)}>Forgot password?</button>}{recoveryOpen && <div className="rounded-2xl bg-[#fbf8f2] p-4"><p className="text-sm text-[#74695b]">Request account recovery. For privacy, we use the same response whether or not an account exists.</p><Button type="button" variant="outline" className="mt-3 w-full" disabled={recovery.isPending || !email} onClick={() => recovery.mutate({ email, role: "customer" })}>Request password help</Button></div>}</div></section></main></StorefrontLayout>;
}
