import { DeliveryTrackingMap } from "@/components/DeliveryTrackingMap";
import { StorefrontLayout } from "@/components/StorefrontLayout";
import { trpc } from "@/lib/trpc";
import { ORDER_STATUS_LABELS, ORDER_STATUSES } from "@shared/restaurant";
import { Check, MapPinned } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function OrderDetail() {
  const [, params] = useRoute("/orders/:orderId");
  const orderId = Number(params?.orderId);
  const detail = trpc.commerce.orders.detail.useQuery({ orderId }, { enabled: Number.isFinite(orderId) });
  const active = detail.data?.order.status === "rider_assigned" || detail.data?.order.status === "out_for_delivery";
  const tracking = trpc.operations.tracking.current.useQuery({ orderId }, { enabled: Number.isFinite(orderId) && active, refetchInterval: active ? 15_000 : false });
  if (detail.isLoading) return <StorefrontLayout><div className="container py-20"><div className="h-64 animate-pulse rounded-3xl bg-[#eadfce]" /></div></StorefrontLayout>;
  if (detail.isError) return <StorefrontLayout><div className="container py-20 text-center"><p className="font-serif text-3xl">Order details could not be loaded</p><button type="button" onClick={() => detail.refetch()} className="mt-4 text-sm font-bold text-[#ae3f25]">Try again</button></div></StorefrontLayout>;
  if (!detail.data) return <StorefrontLayout><div className="container py-20 text-center">Order unavailable. <Link href="/orders" className="text-[#ae3f25]">See your orders</Link></div></StorefrontLayout>;
  const { order, items, history } = detail.data;
  const stage = ORDER_STATUSES.indexOf(order.status);
  return <StorefrontLayout><main className="container py-10 sm:py-14"><Link href="/orders" className="text-xs font-bold text-[#ae3f25]">← All orders</Link><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_360px]"><section><p className="eyebrow">{order.orderNo}</p><h1 className="mt-2 font-serif text-4xl font-semibold">{ORDER_STATUS_LABELS[order.status]}</h1><p className="mt-3 text-sm text-[#74695b]">We’ll keep this timeline updated as your food moves through the restaurant.</p>{active && <div className="mt-7 rounded-3xl bg-white p-6"><div className="flex items-center gap-2"><MapPinned className="h-5 w-5 text-[#ae3f25]" /><h2 className="font-serif text-2xl font-semibold">Live delivery map</h2></div><p className="mt-2 text-sm text-[#74695b]">Rider location is shown only while the rider has actively consented to share it for this delivery.</p><div className="mt-5"><DeliveryTrackingMap destination={tracking.data?.destination ?? null} riderLocation={tracking.data?.riderLocation ?? null} /></div>{tracking.data?.riderLocation ? <p className="mt-3 text-xs font-semibold text-[#658247]">Rider location updated live for this active delivery.</p> : <p className="mt-3 text-xs text-[#74695b]">Waiting for the rider to start live sharing. Your address and order remain available to the rider.</p>}</div>}<div className="mt-8 rounded-3xl bg-white p-6"><h2 className="font-serif text-2xl font-semibold">Order timeline</h2><div className="mt-6 space-y-5">{ORDER_STATUSES.filter(status => !["pending_payment", "cancelled"].includes(status)).map((status, index) => <div key={status} className="flex gap-4"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full ${index <= stage ? "bg-[#ae3f25] text-white" : "bg-[#eee5d8] text-[#8a7e70]"}`}><Check className="h-3.5 w-3.5" /></span><div><p className="text-sm font-bold">{ORDER_STATUS_LABELS[status]}</p>{history.find(entry => entry.status === status)?.note && <p className="mt-1 text-xs text-[#74695b]">{history.find(entry => entry.status === status)?.note}</p>}</div></div>)}</div></div></section><aside className="h-fit rounded-3xl bg-[#272119] p-6 text-[#fff8ef]"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d99b69]">Your order</p><div className="mt-5 space-y-3">{items.map(item => <div key={item.id} className="flex justify-between gap-3 text-sm"><span>{item.quantity} × {item.itemNameSnapshot}</span><span>₹{((item.quantity * item.unitPricePaise) / 100).toFixed(0)}</span></div>)}</div><div className="mt-5 border-t border-white/15 pt-5 font-bold">Total <span className="float-right">₹{(order.grandTotalPaise / 100).toFixed(0)}</span></div><p className="mt-5 text-xs leading-5 text-white/60">Payment: {order.paymentMethod === "stripe" ? "Online card payment" : order.paymentMethod === "cashfree" ? "Cashfree online payment" : "Cash on delivery"}</p></aside></div></main></StorefrontLayout>;
}
