import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { StorefrontLayout } from "@/components/StorefrontLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Bell, MapPin, Package } from "lucide-react";
import { Link } from "wouter";
import { Input } from "@/components/ui/input";
import { useState } from "react";
import { toast } from "sonner";

export default function Profile() { const { user, isAuthenticated, logout } = useAuth(); const notes = trpc.commerce.notifications.list.useQuery(undefined, { enabled: isAuthenticated }); const [name, setName] = useState(user?.name || ""); const [phone, setPhone] = useState(user?.phone || ""); const utils = trpc.useUtils(); const update = trpc.auth.profile.update.useMutation({ onSuccess: () => { utils.auth.me.invalidate(); toast.success("Profile updated"); }, onError: error => toast.error(error.message) }); if (!isAuthenticated) return <StorefrontLayout><div className="container py-20 text-center"><p className="font-serif text-3xl font-semibold">Your account, your orders</p><Button onClick={startLogin} className="mt-6 bg-[#ae3f25]">Sign in</Button></div></StorefrontLayout>; return <StorefrontLayout><main className="container py-10 sm:py-14"><p className="eyebrow">Account</p><h1 className="mt-2 font-serif text-5xl font-semibold">Hello, {user?.name?.split(" ")[0] || "there"}</h1><div className="mt-8 grid gap-5 lg:grid-cols-3"><Link href="/orders" className="rounded-3xl bg-white p-6 transition hover:-translate-y-0.5"><Package className="h-5 w-5 text-[#ae3f25]" /><p className="mt-5 font-serif text-2xl font-semibold">Your orders</p><p className="mt-2 text-sm text-[#74695b]">Track current and past food journeys.</p></Link><Link href="/profile/addresses" className="rounded-3xl bg-white p-6 transition hover:-translate-y-0.5"><MapPin className="h-5 w-5 text-[#ae3f25]" /><p className="mt-5 font-serif text-2xl font-semibold">Addresses</p><p className="mt-2 text-sm text-[#74695b]">Create, update, or choose a delivery address.</p></Link><div className="rounded-3xl bg-white p-6"><Bell className="h-5 w-5 text-[#ae3f25]" /><p className="mt-5 font-serif text-2xl font-semibold">Updates</p><p className="mt-2 text-sm text-[#74695b]">{notes.data?.filter(note => !note.isRead).length || 0} unread account updates.</p></div></div><section className="mt-8 max-w-xl rounded-3xl bg-white p-6"><p className="font-serif text-2xl font-semibold">Personal details</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input value={name} onChange={event => setName(event.target.value)} placeholder="Name" /><Input value={phone} onChange={event => setPhone(event.target.value)} placeholder="Phone" /></div><Button onClick={() => update.mutate({ name, phone })} disabled={update.isPending} className="mt-4 bg-[#ae3f25]">Save details</Button></section><div className="mt-8 rounded-3xl bg-[#272119] p-6 text-[#fff8ef]"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d99b69]">Signed in as</p><p className="mt-3 text-sm font-bold">{user?.email || user?.name}</p><Button onClick={logout} variant="outline" className="mt-5 border-white/20 bg-transparent text-white hover:bg-white hover:text-[#272119]">Sign out</Button></div></main></StorefrontLayout>; }
