import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { useState } from "react";
import { toast } from "sonner";

export function RiderProvisioning() {
  const utils = trpc.useUtils();
  const { data: riders = [] } = trpc.operations.admin.riders.useQuery();
  const [form, setForm] = useState({ name: "", email: "", phone: "", password: "" });
  const [resetForm, setResetForm] = useState({ riderUserId: "", password: "" });
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const provision = trpc.operations.admin.provisionRider.useMutation({ onSuccess: () => { setErrorMessage(null); setForm({ name: "", email: "", phone: "", password: "" }); utils.operations.admin.riders.invalidate(); toast.success("Rider account created"); }, onError: error => { setErrorMessage(error.message); toast.error(error.message); } });
  const reset = trpc.operations.admin.resetRiderPassword.useMutation({ onSuccess: () => { setErrorMessage(null); setResetForm({ riderUserId: "", password: "" }); toast.success("Rider password reset"); }, onError: error => { setErrorMessage(error.message); toast.error(error.message); } });
  return <section className="mt-7 rounded-3xl bg-white p-6"><p className="eyebrow">Delivery team</p><h2 className="mt-2 font-serif text-2xl font-semibold">Provision rider access</h2><p className="mt-2 text-sm text-[#74695b]">Create a rider account with a unique email and a 12+ character password. Share the password privately, then the rider can sign in at the rider workspace.</p><div className="mt-5 grid gap-3 md:grid-cols-2"><Input value={form.name} onChange={event => setForm(current => ({ ...current, name: event.target.value }))} placeholder="Rider name" /><Input value={form.email} onChange={event => setForm(current => ({ ...current, email: event.target.value }))} placeholder="Rider email" type="email" /><Input value={form.phone} onChange={event => setForm(current => ({ ...current, phone: event.target.value }))} placeholder="Phone" /><Input value={form.password} onChange={event => setForm(current => ({ ...current, password: event.target.value }))} placeholder="Temporary password (12+ characters)" type="password" /></div>{errorMessage && <p className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{errorMessage}</p>}<Button type="button" className="mt-4 rounded-xl bg-[#ae3f25]" disabled={provision.isPending || form.password.length < 12} onClick={() => { setErrorMessage(null); provision.mutate(form); }}>Create rider account</Button><div className="mt-8 border-t border-[#eadfce] pt-6"><h3 className="font-serif text-xl font-semibold">Reset rider password</h3><p className="mt-2 text-sm text-[#74695b]">Administrators can reset a rider password. The new password is never displayed, stored in the browser after submission, or returned by the server.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select aria-label="Rider account to reset" value={resetForm.riderUserId} onChange={event => setResetForm(current => ({ ...current, riderUserId: event.target.value }))} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">Choose rider account</option>{riders.map(rider => <option key={rider.id} value={rider.id}>{rider.name || rider.email || `Rider ${rider.id}`}</option>)}</select><Input value={resetForm.password} onChange={event => setResetForm(current => ({ ...current, password: event.target.value }))} placeholder="New rider password (12+ characters)" type="password" autoComplete="new-password" /></div><Button type="button" variant="outline" className="mt-4 rounded-xl" disabled={reset.isPending || !resetForm.riderUserId || resetForm.password.length < 12} onClick={() => { setErrorMessage(null); reset.mutate({ riderUserId: Number(resetForm.riderUserId), password: resetForm.password }); }}>Reset rider password</Button></div></section>;
}
